name: python38
channels:
  - defaults
dependencies:
  - ca-certificates=2021.1.19
  - certifi=2020.12.5
  - openssl=1.1.1i
  - pip=20.3.3
  - python=3.8.5
  - setuptools=52.0.0
  - sqlite=3.33.0
  - vc=14.2
  - vs2015_runtime=14.27.29016
  - wheel=0.36.2
  - wincertstore=0.2
  - zlib=1.2.11
  - pip:
    - aiohttp==3.7.3
    - async-timeout==3.0.1
    - attrs==20.3.0
    - authclient==1.0
    - chardet==3.0.4
    - dataclasses==0.6
    - ecdsa==0.14.1
    - enum-compat==0.0.3
    - future==0.18.2
    - idna==2.10
    - intuit-oauth==1.2.3
    - multidict==5.1.0
    - oauthlib==3.1.0
    - prompter==0.3.10
    - pyasn1==0.4.8
    - pycparser==2.18
    - python-dateutil==2.8.1
    - python-jose==3.2.0
    - python-quickbooks==0.8.4
    - rauth==0.7.3
    - requests==2.25.1
    - requests-oauthlib==1.3.0
    - rsa==4.7
    - simplejson==3.17.2
    - six==1.15.0
    - typing-extensions==3.7.4.3
    - urllib3==1.26.3
    - yarl==1.6.3
